spring.application.name=eureka
server.port = 8761


#le avisa a eureka que este servicio no se tiene que registrar, el va a ser el registry
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false


#cada cuanto eureka recibe las solicitudes de los servicios para registrarse
eureka.instance.lease-renewal-interval-in-seconds=0